#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f Vf1_lights.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_lights.sv f1_fsm.sv delay.sv clktick.sv lfsr.sv --exe f1_lights_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_lights.mk Vf1_lights

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vf1_lights
echo "\nSimulation completed"